### ISSUE TITLE
Breaking changes: Github auth issue

### ISSUE THREAD

**Issue by JacksonBates** [Pairboard/Pairboard#46]
Updating security patches for stale npm modules seems to have introduced breakages.

Attempting to log in with Github auth causes this issue:
```
Error: Expected "payload" to be a plain object.
    at validate (/Users/jacksonbates/dev/Pairboard/node_modules/jsonwebtoken/sign.js:34:11)
    at validatePayload (/Users/jacksonbates/dev/Pairboard/node_modules/jsonwebtoken/sign.js:56:10)
    at Object.module.exports [as sign] (/Users/jacksonbates/dev/Pairboard/node_modules/jsonwebtoken/sign.js:108:7)
    at router.get (/Users/jacksonbates/dev/Pairboard/routes/auth.js:8:21)
    at Layer.handle [as handle_request] (/Users/jacksonbates/dev/Pairboard/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jacksonbates/dev/Pairboard/node_modules/express/lib/router/route.js:137:13)
    at complete (/Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/middleware/authenticate.js:250:13)
    at /Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/middleware/authenticate.js:257:15
    at pass (/Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/authenticator.js:421:14)
    at Authenticator.transformAuthInfo (/Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/authenticator.js:443:5)
    at /Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/middleware/authenticate.js:254:22
    at /Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/http/request.js:60:7
    at pass (/Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/authenticator.js:267:43)
    at serialized (/Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/authenticator.js:276:7)
    at passport.serializeUser (/Users/jacksonbates/dev/Pairboard/server.js:40:3)
    at pass (/Users/jacksonbates/dev/Pairboard/node_modules/passport/lib/authenticator.js:284:9)
```

**Comment by JacksonBates** [comment]
Actually, this was broken before the updates. Need to investigate.
